### ISSUE TITLE
Add support of import of the  ENVIRONMENTAL VARIABLES

### ISSUE THREAD

**Issue by romankrv** [pashky/restclient.el#113]
Urgent !!!

Please, add the possible 
like "Add support of import of the  bash ENVIRONMENTAL VARIABLES"

Thanks

**Comment by pashky** [comment]
Спокойствее, только спокойствее, не шуми :)

Try this:
```
:user := (getenv "USER")
:home := (getenv "HOME")
GET http://httpbin.org/get?data=:user&data=:home
```

No, you can't avoid intermediate assignment to restclient variable. That's because I haven't invented any easy to parse syntax for inline elisp everywhere, and was too lazy to write a proper parser for obvious syntax like `GET http://httpbin.org/get?data=:(getenv "USER")&data=:(getenv "HOME")`.

**Comment by romankrv** [comment]
Nice :)

**Comment by romankrv** [comment]
Good point but documentation needs it. Right?

**Comment by pashky** [comment]
There is a documentation for elisp variables. Putting there everything that elisp can do for you too would be a bit too much, wouldn't it?

**Comment by romankrv** [comment]
Oh boy! 
Of course, you're right. 
Good job, guy!

**Comment by romankrv** [comment]
I get a problem in GUI EMACS that your propose not work. 
:user := (getenv "USER")
How will you do fix it?
Thanks

**Comment by pashky** [comment]
OS? On MacOSX environment for gui apps can be different.

**Comment by pashky** [comment]
I assume it not be restclient but emacs issue anyway, so closing it.
