### ISSUE TITLE
[not-issue] Is it possible to define Var using response?

### ISSUE THREAD

**Issue by liuzhen** [pashky/restclient.el#143]
Sorry for this ticket.

For some reason, every _later_ request requires a token, I want to define a Var at the beginning where a `url' request was to get the token. Is that possible or even valid?

I have tried something like following (excuse my lame elisp):

```
:token := <<
((progn
        (require 'url)
        (require 'json)

        (let ((url-request-method "POST")
        (url-request-data "grant_type=password&username=admin&password=admin_pass")
        (url-interface "oauth/token")))
        (url-retrieve (concat :api :api-version "/" url-interface)
                             'message)))
#
```

**Comment by weissjeffm** [comment]
Actually I just came looking for pretty much the same thing. 

The rest API i'm hitting has an "/auth" endpoint that returns a "session-key" in the response, that needs to be used for all future api calls. Currently, I have to manually copy and paste the key from the response buffer to the restclient-mode buffer.

It would be nice if there was a callback that gets passed the response and has the opportunity to set variables.

**Comment by pashky** [comment]
This is something I always wanted myself but never came around actually implementing, because I couldn't come up with generic enough way to make it useful in many cases. And I figured out that occasional copy/paste isn't too annoying for me personally.

So... I'm not saying "never", but it's not going to happen in foreseeable future. The only option available at the moment is to use `restclient-response-loaded-hook` to find session id in current response buffer with regexp and assign it to some global _elisp_ variable e.g. `(setq my-session-key (match-string 1))`. Then pass it to restclient variable like this `:session-key :=  my-session-key`, and then use `:session-key` in further requests. But this is ugly, will tie your hook to single specific API implementation and that value will not be persistent.

**Comment by liuzhen** [comment]
Thank you for your reply.
