### ISSUE TITLE
Feature request: imenu integration

### ISSUE THREAD

**Issue by Pitometsu** [pashky/restclient.el#65]
Add imenu items according to request commentary titles.

**Comment by IvanMalison** [comment]
Any thoughts about exactly how this should work? Like what should be in each imenu heading?

**Comment by Pitometsu** [comment]
per-http-request-URL for example

**Comment by pashky** [comment]
I've added helm support which I find superior to imenu that doesn't seem to be used much nowdays.
https://github.com/pashky/restclient.el/tree/helm_support

**Comment by IvanMalison** [comment]
> I've added helm support which I find superior to imenu 

comparing imenu and helm doesn't really make sense. I use helm as an imenu frontend. imenu simply offers a way to produce a structured high level breakdown of a file.

imenu is a superior solution because you end up not being coupled to helm when you use imenu. Some people, for example, prefer to use ido for fuzzy completion, and imenu supports this quite naturally.

The other advantage of using imenu is that  it doesn't add helm as a dependency which created the issue in https://github.com/melpa/melpa/pull/3749 .

I'd like to get @purcell 's thoughts on this, since he seems to have a good handle on all of this stuff.

> that doesn't seem to be used much nowdays.

I'm not really sure where you are getting this idea from. imenu is used pretty widely an it is supported by almost every major mode out there.
